# Generated by Django 2.2.5 on 2022-02-05 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ename', models.CharField(max_length=50, verbose_name='emp_name')),
                ('eage', models.IntegerField(verbose_name='emp_age')),
            ],
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=50, verbose_name='city')),
                ('pin', models.IntegerField(verbose_name='pin')),
                ('employee', models.ManyToManyField(related_name='address', to='customer.Employee')),
            ],
        ),
    ]
